"""Added Heirarchacal Attribute to Category

Revision ID: 007d6325ad5c
Revises: 2493ed85e410
Create Date: 2022-12-27 23:46:40.802965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007d6325ad5c'
down_revision = '2493ed85e410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CategoryChild',
    sa.Column('ParentChildId', sa.Integer(), nullable=False),
    sa.Column('ParentId', sa.Integer(), nullable=True),
    sa.Column('ChildId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ChildId'], ['category.id'], ),
    sa.ForeignKeyConstraint(['ParentId'], ['category.id'], ),
    sa.PrimaryKeyConstraint('ParentChildId')
    )
    op.drop_table('Person')
    op.drop_table('PersonChild')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_type', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('category_type')

    op.create_table('PersonChild',
    sa.Column('ParentChildId', sa.INTEGER(), nullable=False),
    sa.Column('ParentId', sa.INTEGER(), nullable=True),
    sa.Column('ChildId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ChildId'], ['Person.PersonId'], ),
    sa.ForeignKeyConstraint(['ParentId'], ['Person.PersonId'], ),
    sa.PrimaryKeyConstraint('ParentChildId')
    )
    op.create_table('Person',
    sa.Column('PersonId', sa.INTEGER(), nullable=False),
    sa.Column('PersonType', sa.VARCHAR(), nullable=True),
    sa.Column('Name', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('PersonId')
    )
    op.drop_table('CategoryChild')
    # ### end Alembic commands ###
