"""Added next/prev url/name attributes

Revision ID: 0f3f73c57460
Revises: 51a07ffa3c59
Create Date: 2023-01-05 16:07:31.011977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3f73c57460'
down_revision = '51a07ffa3c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_page_url', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prev_page_url', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('next_page_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prev_page_name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_page_url', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prev_page_url', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('next_page_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prev_page_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('prev_page_name')
        batch_op.drop_column('next_page_name')
        batch_op.drop_column('prev_page_url')
        batch_op.drop_column('next_page_url')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('prev_page_name')
        batch_op.drop_column('next_page_name')
        batch_op.drop_column('prev_page_url')
        batch_op.drop_column('next_page_url')

    # ### end Alembic commands ###
