"""Added type as well

Revision ID: 1ffd754f74ab
Revises: 0f3f73c57460
Create Date: 2023-01-05 16:37:24.700904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffd754f74ab'
down_revision = '0f3f73c57460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_page_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('next_page_type', sa.String(length=10), nullable=True))
        batch_op.alter_column('next_page_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_page_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('next_page_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('next_page_type')
        batch_op.drop_column('prev_page_type')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('next_page_url',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('next_page_type')
        batch_op.drop_column('prev_page_type')

    # ### end Alembic commands ###
