"""Darkmode added

Revision ID: 201e72d89e0c
Revises: 8c15099f0e82
Create Date: 2023-01-04 22:07:15.457170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201e72d89e0c'
down_revision = '8c15099f0e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('darkmode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('darkmode')

    # ### end Alembic commands ###
