"""Changed Test to Person

Revision ID: 2493ed85e410
Revises: cebe42dbffb7
Create Date: 2022-12-27 23:37:28.746532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2493ed85e410'
down_revision = 'cebe42dbffb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Person',
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('PersonType', sa.String(), nullable=True),
    sa.Column('Name', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PersonId')
    )
    op.create_table('PersonChild',
    sa.Column('ParentChildId', sa.Integer(), nullable=False),
    sa.Column('ParentId', sa.Integer(), nullable=True),
    sa.Column('ChildId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ChildId'], ['Person.PersonId'], ),
    sa.ForeignKeyConstraint(['ParentId'], ['Person.PersonId'], ),
    sa.PrimaryKeyConstraint('ParentChildId')
    )
    op.drop_table('test')
    op.drop_table('ordered_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordered_test',
    sa.Column('parent_id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('PersonChild')
    op.drop_table('Person')
    # ### end Alembic commands ###
