"""First


Revision ID: 36986bb5acd2
Revises: 
Create Date: 2023-01-03 12:02:08.041439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36986bb5acd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorytype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categorytype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_text'), ['text'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('body_main', sa.String(), nullable=True),
    sa.Column('body_draft', sa.String(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_body_draft'), ['body_draft'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_body_main'), ['body_main'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_header'), ['header'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_name'), ['name'], unique=True)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('body_main', sa.String(), nullable=True),
    sa.Column('body_draft', sa.String(), nullable=True),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('categorytype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categorytype_id'], ['categorytype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_body_draft'), ['body_draft'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_body_main'), ['body_main'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_header'), ['header'], unique=False)

    op.create_table('roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('CategoryChild',
    sa.Column('ParentChildId', sa.Integer(), nullable=False),
    sa.Column('ParentId', sa.Integer(), nullable=True),
    sa.Column('ChildId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ChildId'], ['category.id'], ),
    sa.ForeignKeyConstraint(['ParentId'], ['category.id'], ),
    sa.PrimaryKeyConstraint('ParentChildId')
    )
    op.create_table('article_categories',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    op.create_table('saved_articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_articles')
    op.drop_table('article_categories')
    op.drop_table('CategoryChild')
    op.drop_table('roles')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_header'))
        batch_op.drop_index(batch_op.f('ix_category_body_main'))
        batch_op.drop_index(batch_op.f('ix_category_body_draft'))

    op.drop_table('category')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_name'))
        batch_op.drop_index(batch_op.f('ix_article_header'))
        batch_op.drop_index(batch_op.f('ix_article_body_main'))
        batch_op.drop_index(batch_op.f('ix_article_body_draft'))

    op.drop_table('article')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('role')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_text'))
        batch_op.drop_index(batch_op.f('ix_feedback_category'))

    op.drop_table('feedback')
    op.drop_table('categorytype')
    # ### end Alembic commands ###
