"""Removed stuff

Revision ID: 81d9f3b51ba7
Revises: f8bfc8bb6e22
Create Date: 2023-01-12 14:28:46.761494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d9f3b51ba7'
down_revision = 'f8bfc8bb6e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_body_draft')
        batch_op.drop_index('ix_category_body_main')
        batch_op.drop_index('ix_category_category_type')
        batch_op.drop_index('ix_category_header')

    op.drop_table('category')
    op.drop_table('saved_articles')
    op.drop_table('CategoryChild')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index('ix_article_body_draft')
        batch_op.drop_index('ix_article_body_main')
        batch_op.drop_index('ix_article_header')
        batch_op.drop_index('ix_article_name')

    op.drop_table('article')
    op.drop_table('article_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('path', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=False),
    sa.Column('body_main', sa.VARCHAR(), nullable=True),
    sa.Column('body_draft', sa.VARCHAR(), nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), nullable=True),
    sa.Column('header', sa.VARCHAR(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('next_page_url', sa.VARCHAR(length=64), nullable=True),
    sa.Column('prev_page_url', sa.VARCHAR(length=50), nullable=True),
    sa.Column('next_page_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('prev_page_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('prev_page_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('next_page_type', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index('ix_article_name', ['name'], unique=False)
        batch_op.create_index('ix_article_header', ['header'], unique=False)
        batch_op.create_index('ix_article_body_main', ['body_main'], unique=False)
        batch_op.create_index('ix_article_body_draft', ['body_draft'], unique=False)

    op.create_table('CategoryChild',
    sa.Column('ParentChildId', sa.INTEGER(), nullable=False),
    sa.Column('ParentId', sa.INTEGER(), nullable=True),
    sa.Column('ChildId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ChildId'], ['category.id'], ),
    sa.ForeignKeyConstraint(['ParentId'], ['category.id'], ),
    sa.PrimaryKeyConstraint('ParentChildId')
    )
    op.create_table('saved_articles',
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'user_id')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('path', sa.VARCHAR(length=50), nullable=False),
    sa.Column('body_main', sa.VARCHAR(), nullable=True),
    sa.Column('body_draft', sa.VARCHAR(), nullable=True),
    sa.Column('header', sa.VARCHAR(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), nullable=True),
    sa.Column('category_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('next_page_url', sa.VARCHAR(length=50), nullable=True),
    sa.Column('prev_page_url', sa.VARCHAR(length=50), nullable=True),
    sa.Column('next_page_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('prev_page_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('prev_page_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('next_page_type', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('ix_category_header', ['header'], unique=False)
        batch_op.create_index('ix_category_category_type', ['category_type'], unique=False)
        batch_op.create_index('ix_category_body_main', ['body_main'], unique=False)
        batch_op.create_index('ix_category_body_draft', ['body_draft'], unique=False)

    # ### end Alembic commands ###
