"""Added Feedback Table

Revision ID: 87922418c58c
Revises: 007d6325ad5c
Create Date: 2022-12-27 23:51:13.083021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87922418c58c'
down_revision = '007d6325ad5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('text', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_text'), ['text'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_text'))
        batch_op.drop_index(batch_op.f('ix_feedback_category'))

    op.drop_table('feedback')
    # ### end Alembic commands ###
