"""Added order column

Revision ID: 8f2902e5e811
Revises: b7dc4f89b593
Create Date: 2023-01-01 19:22:27.516540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2902e5e811'
down_revision = 'b7dc4f89b593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('order')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
