"""Added url_title and url_name

Revision ID: 9efa39a57edc
Revises: 567245db5d93
Create Date: 2022-12-29 10:04:29.069155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efa39a57edc'
down_revision = '567245db5d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_title', sa.String(length=50)))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_name', sa.String(length=50)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('url_name')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('url_title')

    # ### end Alembic commands ###
