"""Renamed features

Revision ID: a48ec14ea9f3
Revises: b8bb12bfd918
Create Date: 2022-12-31 08:00:03.105574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48ec14ea9f3'
down_revision = 'b8bb12bfd918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_main', sa.String(), nullable=True))
        batch_op.drop_index('ix_article_body')
        batch_op.create_index(batch_op.f('ix_article_body_main'), ['body_main'], unique=False)
        batch_op.drop_column('body')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_main', sa.String(), nullable=True))
        batch_op.drop_index('ix_category_body')
        batch_op.create_index(batch_op.f('ix_category_body_main'), ['body_main'], unique=False)
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_category_body_main'))
        batch_op.create_index('ix_category_body', ['body'], unique=False)
        batch_op.drop_column('body_main')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_article_body_main'))
        batch_op.create_index('ix_article_body', ['body'], unique=False)
        batch_op.drop_column('body_main')

    # ### end Alembic commands ###
