"""empty message

Revision ID: ac290f0fda6a
Revises: 
Create Date: 2023-01-14 20:06:57.135504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac290f0fda6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('body_main',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=64000),
               existing_nullable=True)
        batch_op.alter_column('body_draft',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=64000),
               existing_nullable=True)
        batch_op.alter_column('header',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=64000),
               existing_nullable=True)
        batch_op.drop_index('path')
        batch_op.create_index(batch_op.f('ix_document_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_path'), ['path'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_path'))
        batch_op.drop_index(batch_op.f('ix_document_name'))
        batch_op.drop_index(batch_op.f('ix_document_document_type'))
        batch_op.create_index('path', ['path'], unique=False)
        batch_op.alter_column('header',
               existing_type=sa.String(length=64000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
        batch_op.alter_column('body_draft',
               existing_type=sa.String(length=64000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
        batch_op.alter_column('body_main',
               existing_type=sa.String(length=64000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
