"""Added body_draft

Revision ID: b8bb12bfd918
Revises: cbb46d5407c0
Create Date: 2022-12-31 07:57:20.545978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bb12bfd918'
down_revision = 'cbb46d5407c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_draft', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_article_body_draft'), ['body_draft'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_draft', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_category_body_draft'), ['body_draft'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_body_draft'))
        batch_op.drop_column('body_draft')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_body_draft'))
        batch_op.drop_column('body_draft')

    # ### end Alembic commands ###
