"""Add Test Table

Revision ID: cebe42dbffb7
Revises: d718d599c8ca
Create Date: 2022-12-27 23:20:48.483425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebe42dbffb7'
down_revision = 'd718d599c8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('header', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_body'), ['body'], unique=True)
        batch_op.create_index(batch_op.f('ix_category_header'), ['header'], unique=True)

    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordered_test',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('article_categories',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_categories')
    op.drop_table('ordered_test')
    op.drop_table('test')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_header'))
        batch_op.drop_index(batch_op.f('ix_category_body'))

    op.drop_table('category')
    # ### end Alembic commands ###
