"""Article Table

Revision ID: d718d599c8ca
Revises: 1cb9f50c4e15
Create Date: 2022-12-27 22:32:11.421697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd718d599c8ca'
down_revision = '1cb9f50c4e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_body'), ['body'], unique=True)
        batch_op.create_index(batch_op.f('ix_article_header'), ['header'], unique=True)
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_title'))
        batch_op.drop_index(batch_op.f('ix_article_header'))
        batch_op.drop_index(batch_op.f('ix_article_body'))

    op.drop_table('article')
    # ### end Alembic commands ###
