"""Added saved_articles to User

Revision ID: dfe06a67c9d1
Revises: 87922418c58c
Create Date: 2022-12-28 12:01:17.769072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe06a67c9d1'
down_revision = '87922418c58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
