"""FIXED

Revision ID: f321011365fc
Revises: a48ec14ea9f3
Create Date: 2022-12-31 09:03:47.705906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f321011365fc'
down_revision = 'a48ec14ea9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
