"""update attribute names

Revision ID: f33a41f340a5
Revises: 9efa39a57edc
Create Date: 2022-12-29 16:15:42.772960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33a41f340a5'
down_revision = '9efa39a57edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('path', sa.String(length=50), nullable=True))
        batch_op.drop_index('ix_article_title')
        batch_op.create_index(batch_op.f('ix_article_name'), ['name'], unique=True)
        batch_op.drop_column('title')
        batch_op.drop_column('url_title')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=50), nullable=True))
        batch_op.drop_column('url_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('path')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_title', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_article_name'))
        batch_op.create_index('ix_article_title', ['title'], unique=False)
        batch_op.drop_column('path')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
