"""Adding document table

Revision ID: f8bfc8bb6e22
Revises: 1ffd754f74ab
Create Date: 2023-01-12 13:20:01.408822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bfc8bb6e22'
down_revision = '1ffd754f74ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=250), nullable=False),
    sa.Column('body_main', sa.String(), nullable=True),
    sa.Column('body_draft', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('document_type', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prev_page_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['prev_page_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_body_draft'), ['body_draft'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_body_main'), ['body_main'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_header'), ['header'], unique=False)

    op.create_table('bookmarked_documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarked_documents')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_header'))
        batch_op.drop_index(batch_op.f('ix_document_document_type'))
        batch_op.drop_index(batch_op.f('ix_document_body_main'))
        batch_op.drop_index(batch_op.f('ix_document_body_draft'))

    op.drop_table('document')
    # ### end Alembic commands ###
